package com.bdonor.accountservice.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import java.io.Serializable;

@DynamoDBTable(tableName = "Users")
public class User implements Serializable {

    private static final long serialVersionUID = 1L;

    private String id;
    private String bloodgroup;
    private String firstname;
    private String lastname;
    private String email;
    private String password;
    private String addressline;
    private String postcode;
    private String latitude;
    private String longitude;

    public User() {}

    public User(String bloodgroup, String firstname, String lastname, String email, String password, String addressline, String postcode, String latitude, String longitude) { // Proper Constructor
        this.bloodgroup = bloodgroup;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.password = password;
        this.addressline = addressline;
        this.postcode = postcode;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public User(String bloodgroup, String firstname, String lastname, String email, String password, String addressline, String postcode) { // Test Constructor
        this.bloodgroup = bloodgroup;
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.password = password;
        this.addressline = addressline;
        this.postcode = postcode;
    }



    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getBloodgroup() {
        return bloodgroup;
    }

    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }

    @DynamoDBHashKey(attributeName = "firstname")
    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    @DynamoDBAttribute
    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    @DynamoDBRangeKey
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute
    public String getAddressline() {
        return addressline;
    }

    public void setAddressline(String addressline) {
        this.addressline = addressline;
    }

    @DynamoDBAttribute
    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @DynamoDBAttribute
    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    @DynamoDBAttribute
    public String getLongitude() {
        return longitude;
    }

    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", bloodgroup='" + bloodgroup + '\'' +
                ", firstname='" + firstname + '\'' +
                ", lastname='" + lastname + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", addressline='" + addressline + '\'' +
                ", postcode='" + postcode + '\'' +
                ", latitude='" + latitude + '\'' +
                ", longitude='" + longitude + '\'' +
                '}';
    }


}
