package com.bdonor.accountservice.Models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//import org.springframework.data.annotation.Id;
//import org.springframework.data.mongodb.core.index.IndexDirection;
//import org.springframework.data.mongodb.core.index.Indexed;
////import org.springframework.data.mongodb.core.mapping.Document;


//@Document(collection = "AllUsers")
@DynamoDBTable(tableName = "Users")
public class User {

  //  @Id
    private String _id;
    private String bloodGroup;
    private String firstName; // DO NOT change this, needs to stay firstName
//    @Indexed(direction = IndexDirection.ASCENDING)
    private String surname;
    private String email;
    private String password;
    private String addressline;
    private String postcode;
    private String latitude;
    private String longitude;

    public User() {}

    public User(String bloodGroup, String firstname, String surname, String email, String password, String addressline, String postcode) {
        this.bloodGroup = bloodGroup;
        this.firstName = firstname;
        this.surname = surname;
        this.email = email;
        this.password = password;
        this.addressline = addressline;
        this.postcode = postcode;
    }

    public User(String bloodGroup, String firstname, String surname, String email, String password, String addressline, String postcode, String latitude, String longitude) {
        this.bloodGroup = bloodGroup;
        this.firstName = firstname;
        this.surname = surname;
        this.email = email;
        this.password = password;
        this.addressline = addressline;
        this.postcode = postcode;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return _id;
    }

    public void setId(String id) {
        this._id = _id;
    }

    @DynamoDBAttribute
    public String getBloodGroup() {
        return bloodGroup;
    }

    public void setBloodGroup(String bloodGroup) {
        this.bloodGroup = bloodGroup;
    }

    @DynamoDBAttribute
    public String getFirstname() {
        return firstName;
    }

    public void setFirstname(String firstname) {
        this.firstName = firstname;
    }

    @DynamoDBAttribute
    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @DynamoDBAttribute
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @DynamoDBAttribute
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @DynamoDBAttribute
    public String getAddressline() {
        return addressline;
    }

    public void setAddressline(String addressline) {
        this.addressline = addressline;
    }

    @DynamoDBAttribute
    public String getPostcode() {
        return postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    @DynamoDBAttribute
    public String getLatitude() {
        return latitude;
    }

    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }

    @DynamoDBAttribute
    public String getLongtitude() {
        return longitude;
    }

    public void setLongtitude(String longtitude) {
        this.longitude = longtitude;
    }


    @Override
    public String toString() {
        return "NewUser{" +
                "id='" + _id + '\'' +
                ", bloodGroup='" + bloodGroup + '\'' +
                ", firstname='" + firstName + '\'' +
                ", surname='" + surname + '\'' +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", addressline='" + addressline + '\'' +
                ", postcode='" + postcode + '\'' +
                '}';
    }
}
